# **Experiment: 1**

Aim:-

Task Performed:-

1.Explore Top-5 Data Analytics Libraries in Python (w.r.t Features & Applications)

2.Explore Top-5 Data Analytics Libraries in R (w.r.t Features & Applications)

3.Install 2 Libraries each for Python and R

4.Perform simple experiments on the 2 identified libraries each for Python and R

5.Prepare a document with the Aim, Tasks performed, Program, Output, and Conclusion.









**Task 1 :-**

#Python Libraries
1)Pandas

Pandas is a very popular library for working with data. Its goal is to be the most powerful and flexible open-source tool, and in our opinion, it has reached that goal. DataFrames are at the center of pandas. A DataFrame is structured like a table or spreadsheet. The rows and the columns both have indexes, and you can perform operations on rows or columns separately.
Pandas provide high performance, fast, easy-to-use data structures, and data analysis tools for manipulating numeric data and time series.

2)Numpy

Numpy is the fundamental library of python, used to perform scientific computing. It provides high-performance multidimensional arrays and tools to deal with them. Numpy arrays are fast, easy to understand, and give users the right to perform calculations across arrays.
Using numpy array, we can do arithmetic operation throughtout the array, we don't need to iterate.

3)Scipy

SciPy provides algorithms for optimization, integration, interpolation, eigenvalue problems, algebraic equations, differential equations, statistics and many other classes of problems. The algorithms and data structures provided by SciPy are broadly applicable across domains.SciPy contains modules for optimization, linear algebra, integration, interpolation, special functions, FFT, signal and image processing, ODE solvers and other tasks common in science and engineering.

4)Scikit Learn

Through scikit-learn, we can implement various machine learning models for regression, classification, clustering, and statistical tools for analyzing these models. It also provides functionality for dimensionality reduction, feature selection, feature extraction, ensemble techniques, and inbuilt datasets.Scikit-learn is the most useful and robust library for machine learning in Python. It provides a selection of efficient tools for machine learning and statistical modeling including classification, regression, clustering and dimensionality reduction via a consistence interface in Python.

5)Keras

Keras Applications are deep learning models that are made available alongside pre-trained weights. These models can be used for prediction, feature extraction, and fine-tuning. Weights are downloaded automatically when instantiating a model. Keras contains numerous implementations of commonly used neural-network building blocks such as layers, objectives, activation functions, optimizers, and a host of tools for working with image and text data to simplify programming in deep neural network area.




**Task 2 :-**

# **R Libraries**

1)dplyr

The package "dplyr" comprises many functions that perform mostly used data manipulation operations such as applying filter, selecting specific columns, sorting data, adding or deleting columns and aggregating data. Another most important advantage of this package is that it's very easy to learn and use dplyr functions.

2)tidyr

tidyr is new package that makes it easy to “tidy” your data. Tidy data is data that’s easy to work with: it’s easy to munge (with dplyr), visualise (with ggplot2 or ggvis) and model (with R’s hundreds of modelling packages). tidyr is a one such package which was built for the sole purpose of simplifying the process of creating tidy data. This tutorial provides you with the basic understanding of the four fundamental functions of data tidying that tidyr provides: gather() makes “wide” data longer. spread() makes “long” data wider.

3)readr

The goal of readr is to provide a fast and friendly way to read rectangular data from delimited files, such as comma-separated values (CSV) and tab-separated values (TSV). It is designed to parse many types of data found in the wild, while providing an informative problem report when parsing leads to unexpected results.

4)stringr

Each character in a string has an index number. That index starts at the first character, counting from zero. For example, in s = "Hello string", H has an index of 0, e has an index of 1, l has an index of 2, and so on, up through g with an index of 11. stringr is built on top of stringi, which uses the ICU C library to provide fast, correct implementations of common string manipulations.

5)ggplot2

ggplot2 is a plotting package that provides helpful commands to create complex plots from data in a data frame. It provides a more programmatic interface for specifying what variables to plot, how they are displayed, and general visual properties. ggplot2 plots work best with data in the ‘long’ format, i.e., a column for every variable, and a row for every observation. Well-structured data will save you lots of time when making figures with ggplot2

**Task 3:-**

In [ ]:
#Python
!pip install numpy
!pip install pandas

In [ ]:
#R
install.packages("tidyr")
install.packages("stringr")

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)



**Task 4 :-**

Python (Numpy)

In [ ]:
import numpy as np

In [ ]:
#Converting 1D List into 1D array using numpyc library.
list1=[1,2,3,4]
arr1=np.array(list1)
print(list1)
print(type(list1))
print(arr1)
print(type(arr1))

[1, 2, 3, 4]
<class 'list'>
[1 2 3 4]
<class 'numpy.ndarray'>


In [ ]:
#Converting 2D List into 2D array using numpy
list2=[[1,2,3],[4,5,6]]
arr2=np.array(list2)
print(list2)
print(type(list2))
print(arr2)
print(type(arr2))

[[1, 2, 3], [4, 5, 6]]
<class 'list'>
[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [ ]:
#Performing mathematical operation on all numbers in numpy array at one time
prices=np.array([100,200,300,400])
print(prices-50)

[ 50 150 250 350]


Python (Pandas)

In [ ]:
import pandas as pd

In [ ]:
#Creating a series using numpy array
ages=np.array([20,25,54])
series1= pd.Series(ages)
print(series1)

0    20
1    25
2    54
dtype: int64


In [ ]:
#Giving customized indexes to series
series2=pd.Series(ages,index=["A","B","C"])
print(series2)

A    20
B    25
C    54
dtype: int64


In [ ]:
#Creating Dataframe
df=pd.DataFrame([
    ["Shree",94.83],
    ["Alok",93],
    ["Khalid",94.4]
])
print(df)

        0      1
0   Shree  94.83
1    Alok  93.00
2  Khalid  94.40


R (tidyr)

In [ ]:
#Creating Dataframe
library(tidyr)
n=10
tidyrDf= data.frame(
  S.No = c(1:n),
  Group.1 = c(32, 500, 76, 212, 64,
              200, 72, 40, 90, 183),
  Group.2 = c(72, 89, 59, 334, 90,
              101, 178, 233, 52, 200),
  Group.3 = c(29, 101, 239, 289, 176,
              264, 100, 109, 199, 81)
)
tidyrDf

S.No Group.1 Group.2 Group.3
1   1    32      72      29    
2   2   500      89     101    
3   3    76      59     239    
4   4   212     334     289    
5   5    64      90     176    
6   6   200     101     264    
7   7    72     178     100    
8   8    40     233     109    
9   9    90      52     199    
10 10   183     200      81

R (stringr)

In [ ]:
library(stringr)

In [ ]:
#Calculating length of string
str_length("Hello")

[1] 5

In [ ]:
#Creating Substring
string1 <- "Shreeprasad Navare"
len <- nchar(string1)
print(substr(string1,1,5))

[1] "Shree"


Coclusion:-
Identified the Data Analytics Libraries in Python and R

Performed simple experiments with these libraries in Python and R
